### ISSUE TITLE
some error in src/src/Optimization/SCCPSolver.cc

### ISSUE THREAD

**Issue by Kuznetsov2100** [ImmanuelHaffner/JACCo-old#1]
In the line 313, the parameter in the function addToWorkList should delete the const,because this is not compatible with the variable BBExecutable's element type .
Then in the line 315,the expression in the if() should be BBExecutable.insert( BB ).second,becase when the insertion takes place , it  returns a type of std::pair<iterator, bool>.

**Comment by ImmanuelHaffner** [comment]
What do you mean with "the function addToWorkList should delete the const"? Do you mean the const-qualifier of the Parameter should be removed?
You are right, `BBExecutable` is a `SmallPtrSet`; its `insert()` function returns a `std::pair` and as such, `.second` should be used. Thanks for the remark.

This project is fairly old and has not been updated to work with current LLVM. (We worked with LLVM 3.3 i think. Try linking JACCo against that version. I am pretty sure SmallPtrSet worked differently back then...)

I will *NOT* update this project, as its semantic analysis part is straight out of hell. I currently reimplement JACCo from scratch. If you are interested in this project, let me know.

**Comment by Kuznetsov2100** [comment]
I am Learning to make a compiler of a subset lanuage of C,but I am not
familiar with the assembly language,so I tried to use the llvm to solve the
part of backend .It took me several days to read your project,because of
the llvm version conflict,I got stuck in the mud of many conflict errors.As
you can see,sorry about my Chinese English,I just a beginner of
programming.Thanks about your reply to let me know the details of your
project.

Immanuel Haffner notifications@github.com于2015年9月30日周三 17:57写道：
